name: dev
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切代码到 runner
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
      # 下载 git submodule
      - name: Update submodules
        run: |
          git submodule update --remote
      # 使用 node 16.5.0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.5.0"
      # npm install
      - name: Install npm dependencies
        run: npm install
      # 打包项目
      - name: Run build task
        run: npm run build
      # 复制打包后的代码到服务器
      - name: copy file  via ssh key
        uses: appleboy/scp-action@master
        with:
          source: "web-node/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/dev/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
