# action 的名称
name: github

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 切代码到 runner
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      # 下载 git submodule
      - name: Update submodules
        run: |
          git submodule update --remote
      # 使用 node 16.5.0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.5.0"
      # npm install
      - name: Build
        run: npm install && npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        # 使用别人写好的一个 action
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 打包后的文件部署到哪个分支上
          BRANCH: gh-pages
          # 打包后的文件在哪里
          FOLDER: web-node
