name: prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切代码到 runner
      - uses: actions/checkout@v1
        with:
          submodules: true
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node 16.5.0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.5.0"
      # npm install
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build
      - name: copy file  via ssh key
        uses: appleboy/scp-action@master
        with:
          source: "web-node/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/prod/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
