name: uat
on:
  push:
    branches:
      - uat
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切代码到 runner
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      # 下载 git submodule
      - name: Update submodules
        run: |
          git submodule update --remote
      # 使用 node 16.5.0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.5.0"
      # npm install
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build
      - name: copy file  via ssh key
        uses: appleboy/scp-action@master
        with:
          source: "web-node/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/uat/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
